package ${groupId}.${rootArtifactId}.service;

import ${groupId}.${rootArtifactId}.api.$service;

/**
 * $service service implementation
 *
 * @author Generated by the Rio Archetype
 */
public class ${service}Impl implements $service {

}
